stages:
- name: Build Container
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: myproject
      registry: harbor.kacsh.com
  when:
    branch:
      include:
      - master
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/deployment.yaml
- name: Build something
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo ${FIRST_KEY} && echo ${SECOND_KEY}
    env:
      FIRST_KEY: Hi
      SECOND_KEY: Monkeys
timeout: 60
notification: {}
