stages:
- name: Build Container
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: harbor.kacsh.com
  when:
    branch:
      include:
      - master
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#rancher-notifications'
    notifier: c-55nbm:n-zp4hf
  condition:
  - Success
  - Changed
  - Failed
