version: 2.1

anchors:
  context: &context
    context: rancher2_pipeline_demo
    filters:
      branches:
        only: master

orbs:
  om-common-build: order-metrics/om-common-build@0.0
  om-ecr: order-metrics/om-ecr@0.0
  om-slack: order-metrics/om-slack@0.0

workflows:
  build:
    jobs:
    - om-ecr/build-push:
        <<: *context
        path: ./
        dockerfile: ./docker/Dockerfile
        docker-layer-caching: false
        tag: test
        send-success-message: true