version: 2.1

anchors:
  context: &context
    context: rancher2_pipeline_demo
    filters:
      branches:
        only: master
        
orbs:
  slack: circleci/slack@3.4.2
  om-common-build: order-metrics/om-common-build@0.0
  om-ecr: order-metrics/om-ecr@0.0

workflows:
  build:
    jobs:
    - om-ecr/build-push:
        <<: *context
        path: ./docker
        dockerfile: ./docker/Dockerfile
        docker-layer-caching: false
        tag: test