apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICENAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${SERVICENAME}
  replicas: 3
  template:
    metadata:
      labels:
        app: ${SERVICENAME}
    spec:
      containers:
      - name: ${SERVICENAME}
        imagePullPolicy: Always
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}

---
kind: Service
apiVersion: v1
metadata:
  name: ${SERVICENAME}-service
  namespace: ${NAMESPACE}
  annotations:
    external-dns.alpha.kubernetes.io: ${HOST_NAME}
spec:
  selector:
    app: nginx
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${HOST_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${HOST_NAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${SERVICENAME}-service
              servicePort: 80
